-- Suporte a múltiplas receitas/solicitações de exames por atendimento
CREATE TABLE IF NOT EXISTS public."CONSULTA_DOCUMENTO" (
  "ID_DOC_CONS"    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "ID_CONS"        uuid NOT NULL REFERENCES public."CONSULTA"("ID_CONS") ON DELETE CASCADE,
  "ID_EMP"         uuid NOT NULL,
  "TIPO"           text NOT NULL CHECK ("TIPO" IN ('RECEITA','EXAME')),
  "CONTEUDO"       text NOT NULL,
  "DTCRI_DOC_CONS" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_consulta_documento_cons ON public."CONSULTA_DOCUMENTO"("ID_CONS");

ALTER TABLE public."CONSULTA_DOCUMENTO" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "CONSULTA_DOCUMENTO_select" ON public."CONSULTA_DOCUMENTO";
CREATE POLICY "CONSULTA_DOCUMENTO_select" ON public."CONSULTA_DOCUMENTO"
  FOR SELECT USING (get_my_tipo_usu() = 'ADMIN_GLOBAL' OR "ID_EMP" = get_my_empresa_id());

DROP POLICY IF EXISTS "CONSULTA_DOCUMENTO_insert" ON public."CONSULTA_DOCUMENTO";
CREATE POLICY "CONSULTA_DOCUMENTO_insert" ON public."CONSULTA_DOCUMENTO"
  FOR INSERT WITH CHECK (
    get_my_tipo_usu() = 'ADMIN_GLOBAL'
    OR ("ID_EMP" = get_my_empresa_id() AND get_my_tipo_usu() = ANY (ARRAY['ADMIN_EMPRESA','SECRETARIA','PROFISSIONAL']))
  );

DROP POLICY IF EXISTS "CONSULTA_DOCUMENTO_update" ON public."CONSULTA_DOCUMENTO";
CREATE POLICY "CONSULTA_DOCUMENTO_update" ON public."CONSULTA_DOCUMENTO"
  FOR UPDATE USING (get_my_tipo_usu() = 'ADMIN_GLOBAL' OR "ID_EMP" = get_my_empresa_id());

DROP POLICY IF EXISTS "CONSULTA_DOCUMENTO_delete" ON public."CONSULTA_DOCUMENTO";
CREATE POLICY "CONSULTA_DOCUMENTO_delete" ON public."CONSULTA_DOCUMENTO"
  FOR DELETE USING (get_my_tipo_usu() = 'ADMIN_GLOBAL' OR "ID_EMP" = get_my_empresa_id());

-- Backfill dos dados existentes (colunas antigas continuam em CONSULTA, apenas não são mais escritas)
INSERT INTO public."CONSULTA_DOCUMENTO" ("ID_CONS","ID_EMP","TIPO","CONTEUDO")
SELECT "ID_CONS","ID_EMP",'RECEITA',"PRESCRICAO"
FROM public."CONSULTA" WHERE "PRESCRICAO" IS NOT NULL AND btrim("PRESCRICAO") <> '';

INSERT INTO public."CONSULTA_DOCUMENTO" ("ID_CONS","ID_EMP","TIPO","CONTEUDO")
SELECT "ID_CONS","ID_EMP",'EXAME',"SOLICITACAO_EXAMES"
FROM public."CONSULTA" WHERE "SOLICITACAO_EXAMES" IS NOT NULL AND btrim("SOLICITACAO_EXAMES") <> '';
